"""Canonical environment facts for every CrossMaze variant.

This module owns the environment side of each variant: maze layout, size
scaling, Gymnasium env id and construction kwargs, offline dataset id or
local dataset directory name, and (for AntMaze) the fixed evaluation
start/goal cells passed through `reset(options=...)`. Prompt copywriting
(env names, structure descriptions) stays on the repo side.

AntMaze evaluation deliberately uses the same maps the D4RL offline data
was collected on (the official eval UMaze map is mirrored relative to the
collection map); eval start/goal cells are recorded as coordinates instead
of "r"/"g" map markers.
"""

from crossmaze import maps as _maps

POINTMAZE_ENV_FACTS = {
    "open": {
        "kind": "remote",
        "dataset_id": "D4RL/pointmaze/open-v2",
        "env_id": "PointMaze_Open-v3",
        "maze_map": _maps.POINTMAZE_OPEN,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
    },
    "open-dense": {
        "kind": "remote",
        "dataset_id": "D4RL/pointmaze/open-dense-v2",
        "env_id": "PointMaze_OpenDense-v3",
        "maze_map": _maps.POINTMAZE_OPEN,
        "maze_size_scaling": 1.0,
        "reward_type": "dense",
    },
    "umaze": {
        "kind": "remote",
        "dataset_id": "D4RL/pointmaze/umaze-v2",
        "env_id": "PointMaze_UMaze-v3",
        "maze_map": _maps.POINTMAZE_UMAZE,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
    },
    "umaze-dense": {
        "kind": "remote",
        "dataset_id": "D4RL/pointmaze/umaze-dense-v2",
        "env_id": "PointMaze_UMazeDense-v3",
        "maze_map": _maps.POINTMAZE_UMAZE,
        "maze_size_scaling": 1.0,
        "reward_type": "dense",
    },
    "medium": {
        "kind": "remote",
        "dataset_id": "D4RL/pointmaze/medium-v2",
        "env_id": "PointMaze_Medium-v3",
        "maze_map": _maps.POINTMAZE_MEDIUM,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
    },
    "medium-dense": {
        "kind": "remote",
        "dataset_id": "D4RL/pointmaze/medium-dense-v2",
        "env_id": "PointMaze_MediumDense-v3",
        "maze_map": _maps.POINTMAZE_MEDIUM,
        "maze_size_scaling": 1.0,
        "reward_type": "dense",
    },
    "large": {
        "kind": "remote",
        "dataset_id": "D4RL/pointmaze/large-v2",
        "env_id": "PointMaze_Large-v3",
        "maze_map": _maps.POINTMAZE_LARGE,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
    },
    "large-dense": {
        "kind": "remote",
        "dataset_id": "D4RL/pointmaze/large-dense-v2",
        "env_id": "PointMaze_LargeDense-v3",
        "maze_map": _maps.POINTMAZE_LARGE,
        "maze_size_scaling": 1.0,
        "reward_type": "dense",
    },
    "local-medium": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-local-medium-v0",
        "maze_map": _maps.POINTMAZE_MEDIUM,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_MEDIUM,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 600,
        },
    },
    "local-layout-01": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-local-layout-01-v0",
        "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_01,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_01,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 384,
        },
    },
    "local-layout-02": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-local-layout-02-v0",
        "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_02,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_02,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 480,
        },
    },
    "local-layout-03": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-local-layout-03-v0",
        "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_03,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_03,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 486,
        },
    },
    "local-layout-04": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-local-layout-04-v0",
        "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_04,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_04,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 480,
        },
    },
    "local-layout-05": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-local-layout-05-v0",
        "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_05,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_05,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 720,
        },
    },
    "local-layout-06": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-local-layout-06-v0",
        "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_06,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_06,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 726,
        },
    },
    "local-layout-07": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-local-layout-07-v0",
        "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_07,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_07,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 624,
        },
    },
    "local-layout-08": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-local-layout-08-v0",
        "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_08,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_08,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 1014,
        },
    },
    "local-layout-09": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-local-layout-09-v0",
        "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_09,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_09,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 1008,
        },
    },
    "local-layout-10": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-local-layout-10-v0",
        "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_10,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_10,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 648,
        },
    },
    "local-layout-11": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-local-layout-11-v0",
        "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_11,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_11,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 600,
        },
    },
    "local-layout-12": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-local-layout-12-v0",
        "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_12,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_12,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 792,
        },
    },
    "local-layout-13": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-local-layout-13-v0",
        "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_13,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_13,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 1400,
        },
    },
    "test-layout-01": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-test-layout-01-v0",
        "maze_map": _maps.POINTMAZE_TEST_LAYOUT_01,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_TEST_LAYOUT_01,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 780,
        },
    },
    "test-layout-02": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-test-layout-02-v0",
        "maze_map": _maps.POINTMAZE_TEST_LAYOUT_02,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_TEST_LAYOUT_02,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 576,
        },
    },
    "test-layout-03": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-test-layout-03-v0",
        "maze_map": _maps.POINTMAZE_TEST_LAYOUT_03,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_TEST_LAYOUT_03,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 1014,
        },
    },
    "local-layoutV2-01": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-local-layoutV2-01-v0",
        "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_V2_01,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_V2_01,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 1014,
        },
    },
    "local-layoutV2-02": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-local-layoutV2-02-v0",
        "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_V2_02,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_V2_02,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 858,
        },
    },
    "local-layoutV2-03": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-local-layoutV2-03-v0",
        "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_V2_03,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_V2_03,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 858,
        },
    },
    "local-layoutV2-04": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-local-layoutV2-04-v0",
        "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_V2_04,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_V2_04,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 858,
        },
    },
    "local-layoutV2-05": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-local-layoutV2-05-v0",
        "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_V2_05,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_V2_05,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 990,
        },
    },
    "local-layoutV2-06": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-local-layoutV2-06-v0",
        "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_V2_06,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_V2_06,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 990,
        },
    },
    "local-layoutV2-07": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-local-layoutV2-07-v0",
        "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_V2_07,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_V2_07,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 1170,
        },
    },
    "local-layoutV2-08": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-local-layoutV2-08-v0",
        "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_V2_08,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_V2_08,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 990,
        },
    },
    "local-layoutV2-09": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-local-layoutV2-09-v0",
        "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_V2_09,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_V2_09,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 1170,
        },
    },
    "local-layoutV2-10": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-local-layoutV2-10-v0",
        "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_V2_10,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_V2_10,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 1170,
        },
    },
    "local-layoutV2-11": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-local-layoutV2-11-v0",
        "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_V2_11,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_V2_11,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 1350,
        },
    },
    "local-layoutV2-12": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-local-layoutV2-12-v0",
        "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_V2_12,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_LOCAL_LAYOUT_V2_12,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 1170,
        },
    },
    "test-layoutV2-01": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-test-layoutV2-01-v0",
        "maze_map": _maps.POINTMAZE_TEST_LAYOUT_V2_01,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_TEST_LAYOUT_V2_01,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 726,
        },
    },
    "test-layoutV2-02": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-test-layoutV2-02-v0",
        "maze_map": _maps.POINTMAZE_TEST_LAYOUT_V2_02,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_TEST_LAYOUT_V2_02,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 726,
        },
    },
    "test-layoutV2-03": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-test-layoutV2-03-v0",
        "maze_map": _maps.POINTMAZE_TEST_LAYOUT_V2_03,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_TEST_LAYOUT_V2_03,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 1014,
        },
    },
    "test-layoutV2-04": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-test-layoutV2-04-v0",
        "maze_map": _maps.POINTMAZE_TEST_LAYOUT_V2_04,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_TEST_LAYOUT_V2_04,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 810,
        },
    },
    "test-layoutV2-05": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-test-layoutV2-05-v0",
        "maze_map": _maps.POINTMAZE_TEST_LAYOUT_V2_05,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_TEST_LAYOUT_V2_05,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 1350,
        },
    },
    "test-layoutV2-06": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-test-layoutV2-06-v0",
        "maze_map": _maps.POINTMAZE_TEST_LAYOUT_V2_06,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_TEST_LAYOUT_V2_06,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 1170,
        },
    },
    "local-EXturn": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-local-EXturn-v0",
        "maze_map": _maps.POINTMAZE_LOCAL_EXTURN,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_LOCAL_EXTURN,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 726,
        },
    },
    "test-EXturn": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-test-EXturn-v0",
        "maze_map": _maps.POINTMAZE_TEST_EXTURN,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_TEST_EXTURN,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 858,
        },
    },
    "local-EXturn-simple": {
        "kind": "local",
        "dataset_path": "local_datasets/pointmaze-local-EXturn-simple-v0",
        "maze_map": _maps.POINTMAZE_LOCAL_EXTURN_SIMPLE,
        "maze_size_scaling": 1.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "PointMaze_UMaze-v3",
            "maze_map": _maps.POINTMAZE_LOCAL_EXTURN_SIMPLE,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": True,
            "max_episode_steps": 300,
        },
    },
}

ANTMAZE_ENV_FACTS = {
    "umaze": {
        "kind": "remote",
        "dataset_id": "D4RL/antmaze/umaze-v1",
        "env_id": "AntMaze_UMaze-v4",
        "maze_map": _maps.ANTMAZE_UMAZE,
        "maze_size_scaling": 4.0,
        "reward_type": "sparse",
        "env_kwargs": {
            "maze_map": _maps.ANTMAZE_UMAZE,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": False,
        },
        "eval_reset_cell": (1, 1),
        "eval_goal_cell": (3, 1),
    },
    "umaze-diverse": {
        "kind": "remote",
        "dataset_id": "D4RL/antmaze/umaze-diverse-v1",
        "env_id": "AntMaze_UMaze-v4",
        "maze_map": _maps.ANTMAZE_UMAZE,
        "maze_size_scaling": 4.0,
        "reward_type": "sparse",
        "env_kwargs": {
            "maze_map": _maps.ANTMAZE_UMAZE,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": False,
        },
        "eval_reset_cell": (1, 1),
        "eval_goal_cell": (3, 1),
    },
    "medium-play": {
        "kind": "remote",
        "dataset_id": "D4RL/antmaze/medium-play-v1",
        "env_id": "AntMaze_Medium-v4",
        "maze_map": _maps.ANTMAZE_MEDIUM,
        "maze_size_scaling": 4.0,
        "reward_type": "sparse",
        "env_kwargs": {
            "maze_map": _maps.ANTMAZE_MEDIUM,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": False,
        },
        "eval_reset_cell": (1, 1),
        "eval_goal_cell": (6, 6),
    },
    "medium-diverse": {
        "kind": "remote",
        "dataset_id": "D4RL/antmaze/medium-diverse-v1",
        "env_id": "AntMaze_Medium_Diverse_GR-v4",
        "maze_map": _maps.ANTMAZE_MEDIUM,
        "maze_size_scaling": 4.0,
        "reward_type": "sparse",
        "env_kwargs": {
            "maze_map": _maps.ANTMAZE_MEDIUM,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": False,
        },
        "eval_reset_cell": (1, 1),
        "eval_goal_cell": (6, 6),
    },
    "large-play": {
        "kind": "remote",
        "dataset_id": "D4RL/antmaze/large-play-v1",
        "env_id": "AntMaze_Large-v4",
        "maze_map": _maps.ANTMAZE_LARGE,
        "maze_size_scaling": 4.0,
        "reward_type": "sparse",
        "env_kwargs": {
            "maze_map": _maps.ANTMAZE_LARGE,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": False,
        },
        "eval_reset_cell": (1, 1),
        "eval_goal_cell": (7, 9),
    },
    "large-diverse": {
        "kind": "remote",
        "dataset_id": "D4RL/antmaze/large-diverse-v1",
        "env_id": "AntMaze_Large_Diverse_GR-v4",
        "maze_map": _maps.ANTMAZE_LARGE,
        "maze_size_scaling": 4.0,
        "reward_type": "sparse",
        "env_kwargs": {
            "maze_map": _maps.ANTMAZE_LARGE,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": False,
        },
        "eval_reset_cell": (1, 1),
        "eval_goal_cell": (7, 9),
    },
    "local-layout-01": {
        "kind": "local",
        "dataset_path": "local_datasets/antmaze-local-layout-01-v0",
        "maze_map": _maps.ANTMAZE_LOCAL_LAYOUT_01,
        "maze_size_scaling": 4.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "AntMaze_UMaze-v4",
            "maze_map": _maps.ANTMAZE_LOCAL_LAYOUT_01,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": False,
            "max_episode_steps": 1000,
        },
        "eval_reset_cell": (1, 1),
        "eval_goal_cell": (7, 11),
    },
    "local-layout-02": {
        "kind": "local",
        "dataset_path": "local_datasets/antmaze-local-layout-02-v0",
        "maze_map": _maps.ANTMAZE_LOCAL_LAYOUT_02,
        "maze_size_scaling": 4.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "AntMaze_UMaze-v4",
            "maze_map": _maps.ANTMAZE_LOCAL_LAYOUT_02,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": False,
            "max_episode_steps": 1000,
        },
        "eval_reset_cell": (7, 1),
        "eval_goal_cell": (5, 11),
    },
    "local-layout-03": {
        "kind": "local",
        "dataset_path": "local_datasets/antmaze-local-layout-03-v0",
        "maze_map": _maps.ANTMAZE_LOCAL_LAYOUT_03,
        "maze_size_scaling": 4.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "AntMaze_UMaze-v4",
            "maze_map": _maps.ANTMAZE_LOCAL_LAYOUT_03,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": False,
            "max_episode_steps": 1000,
        },
        "eval_reset_cell": (7, 1),
        "eval_goal_cell": (1, 11),
    },
    "local-layout-04": {
        "kind": "local",
        "dataset_path": "local_datasets/antmaze-local-layout-04-v0",
        "maze_map": _maps.ANTMAZE_LOCAL_LAYOUT_04,
        "maze_size_scaling": 4.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "AntMaze_UMaze-v4",
            "maze_map": _maps.ANTMAZE_LOCAL_LAYOUT_04,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": False,
            "max_episode_steps": 1000,
        },
        "eval_reset_cell": (7, 1),
        "eval_goal_cell": (1, 11),
    },
    "local-layout-05": {
        "kind": "local",
        "dataset_path": "local_datasets/antmaze-local-layout-05-v0",
        "maze_map": _maps.ANTMAZE_LOCAL_LAYOUT_05,
        "maze_size_scaling": 4.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "AntMaze_UMaze-v4",
            "maze_map": _maps.ANTMAZE_LOCAL_LAYOUT_05,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": False,
            "max_episode_steps": 1000,
        },
        "eval_reset_cell": (1, 5),
        "eval_goal_cell": (7, 11),
    },
    "local-layout-06": {
        "kind": "local",
        "dataset_path": "local_datasets/antmaze-local-layout-06-v0",
        "maze_map": _maps.ANTMAZE_LOCAL_LAYOUT_06,
        "maze_size_scaling": 4.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "AntMaze_UMaze-v4",
            "maze_map": _maps.ANTMAZE_LOCAL_LAYOUT_06,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": False,
            "max_episode_steps": 1000,
        },
        "eval_reset_cell": (3, 1),
        "eval_goal_cell": (7, 11),
    },
    "local-layout-07": {
        "kind": "local",
        "dataset_path": "local_datasets/antmaze-local-layout-07-v0",
        "maze_map": _maps.ANTMAZE_LOCAL_LAYOUT_07,
        "maze_size_scaling": 4.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "AntMaze_UMaze-v4",
            "maze_map": _maps.ANTMAZE_LOCAL_LAYOUT_07,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": False,
            "max_episode_steps": 1000,
        },
        "eval_reset_cell": (1, 11),
        "eval_goal_cell": (1, 1),
    },
    "local-layout-08": {
        "kind": "local",
        "dataset_path": "local_datasets/antmaze-local-layout-08-v0",
        "maze_map": _maps.ANTMAZE_LOCAL_LAYOUT_08,
        "maze_size_scaling": 4.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "AntMaze_UMaze-v4",
            "maze_map": _maps.ANTMAZE_LOCAL_LAYOUT_08,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": False,
            "max_episode_steps": 1000,
        },
        "eval_reset_cell": (1, 11),
        "eval_goal_cell": (7, 9),
    },
    "local-layout-09": {
        "kind": "local",
        "dataset_path": "local_datasets/antmaze-local-layout-09-v0",
        "maze_map": _maps.ANTMAZE_LOCAL_LAYOUT_09,
        "maze_size_scaling": 4.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "AntMaze_UMaze-v4",
            "maze_map": _maps.ANTMAZE_LOCAL_LAYOUT_09,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": False,
            "max_episode_steps": 1000,
        },
        "eval_reset_cell": (6, 11),
        "eval_goal_cell": (1, 1),
    },
    "test-layout-01": {
        "kind": "local",
        "dataset_path": "local_datasets/antmaze-test-layout-01-v0",
        "maze_map": _maps.ANTMAZE_TEST_LAYOUT_01,
        "maze_size_scaling": 4.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "AntMaze_UMaze-v4",
            "maze_map": _maps.ANTMAZE_TEST_LAYOUT_01,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": False,
            "max_episode_steps": 1000,
        },
        "eval_reset_cell": (5, 1),
        "eval_goal_cell": (1, 11),
    },
    "test-layout-02": {
        "kind": "local",
        "dataset_path": "local_datasets/antmaze-test-layout-02-v0",
        "maze_map": _maps.ANTMAZE_TEST_LAYOUT_02,
        "maze_size_scaling": 4.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "AntMaze_UMaze-v4",
            "maze_map": _maps.ANTMAZE_TEST_LAYOUT_02,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": False,
            "max_episode_steps": 1000,
        },
        "eval_reset_cell": (7, 1),
        "eval_goal_cell": (1, 11),
    },
    "test-layout-03": {
        "kind": "local",
        "dataset_path": "local_datasets/antmaze-test-layout-03-v0",
        "maze_map": _maps.ANTMAZE_TEST_LAYOUT_03,
        "maze_size_scaling": 4.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "AntMaze_UMaze-v4",
            "maze_map": _maps.ANTMAZE_TEST_LAYOUT_03,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": False,
            "max_episode_steps": 1000,
        },
        "eval_reset_cell": (7, 1),
        "eval_goal_cell": (7, 11),
    },
    "test-layout-04": {
        "kind": "local",
        "dataset_path": "local_datasets/antmaze-test-layout-04-v0",
        "maze_map": _maps.ANTMAZE_TEST_LAYOUT_04,
        "maze_size_scaling": 4.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "AntMaze_UMaze-v4",
            "maze_map": _maps.ANTMAZE_TEST_LAYOUT_04,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": False,
            "max_episode_steps": 1000,
        },
        "eval_reset_cell": (7, 1),
        "eval_goal_cell": (5, 7),
    },
    "ultra": {
        "kind": "local",
        "dataset_path": "local_datasets/antmaze-ultra-v0",
        "maze_map": _maps.ANTMAZE_ULTRA,
        "maze_size_scaling": 4.0,
        "reward_type": "sparse",
        "env_paras": {
            "id": "AntMaze_UMaze-v4",
            "maze_map": _maps.ANTMAZE_ULTRA,
            "reward_type": "sparse",
            "continuing_task": True,
            "reset_target": False,
            "max_episode_steps": 2000,
        },
        "eval_reset_cell": (1, 1),
        "eval_goal_cell": (10, 14),
    },
}

ENV_FACTS = {
    "pointmaze": POINTMAZE_ENV_FACTS,
    "antmaze": ANTMAZE_ENV_FACTS,
}


def list_variants(env_family: str) -> list[str]:
    if env_family not in ENV_FACTS:
        raise ValueError(
            f"Unknown env_family: {env_family!r}. Available: {list(ENV_FACTS)}"
        )
    return list(ENV_FACTS[env_family])


def get_env_facts(env_family: str, variant: str) -> dict:
    facts_by_variant = ENV_FACTS.get(env_family)
    if facts_by_variant is None:
        raise ValueError(
            f"Unknown env_family: {env_family!r}. Available: {list(ENV_FACTS)}"
        )
    facts = facts_by_variant.get(variant)
    if facts is None:
        raise ValueError(
            f"Unknown variant {variant!r} for env_family={env_family!r}. "
            f"Available: {list(facts_by_variant)}"
        )
    return facts


def eval_env_spec(env_family: str, variant: str) -> tuple[str, dict]:
    """Gymnasium env id + construction kwargs for evaluation rollout."""
    facts = get_env_facts(env_family, variant)
    if facts["kind"] == "local":
        env_kwargs = {key: value for key, value in facts["env_paras"].items() if key != "id"}
        return facts["env_paras"]["id"], env_kwargs
    return facts["env_id"], dict(facts.get("env_kwargs") or {})


def eval_reset_options(env_family: str, variant: str) -> dict | None:
    """Fixed eval start/goal cells as `reset(options=...)`, if the variant has them."""
    facts = get_env_facts(env_family, variant)
    reset_cell = facts.get("eval_reset_cell")
    goal_cell = facts.get("eval_goal_cell")
    if reset_cell is None and goal_cell is None:
        return None
    options = {}
    if reset_cell is not None:
        options["reset_cell"] = [int(reset_cell[0]), int(reset_cell[1])]
    if goal_cell is not None:
        options["goal_cell"] = [int(goal_cell[0]), int(goal_cell[1])]
    return options
