# Override relative to config.isb.ant.0.0.0.yaml.
# Merge with: --config configs/train/config.isb.ant.0.0.0.yaml configs/train/config.isb.ant.0.0.1.yaml
min_lr_ratio: 0.1
lr_scheduler_type: cosine
lr_decay_ref_epochs: 9.0
warmup_ratio: 0.1
warmup_ratio_ref_epoch: 1.0
