# Override relative to config.isb.ant.0.0.0.yaml.
# Merge with: --config configs/train/config.isb.ant.0.0.0.yaml configs/train/config.isb.ant.0.1.0.yaml
config_delete_keys:
- action_query_len
- action_head_num_blocks
- action_head_dropout
- action_head_weight_decay
- gaussian_log_std_init
- gaussian_log_std_min
- gaussian_log_std_max
prompt_templete_index:
- bin_full_sensing
action_token_mode: simple_mtp_bin
action_num_bins: 50
new_token: false
action_bin_min: -1.0
action_bin_max: 1.0
mtp_lcm_weight: 0.1
min_lr_ratio: 0.1
lr_scheduler_type: cosine
lr_decay_ref_epochs: 9.0
warmup_ratio: 0.1
warmup_ratio_ref_epoch: 1.0
lora_r: 128
lora_alpha: 128
